"""Markdown exporter for multi-agent research reports."""

from models.report import MultiAgentReport


def to_markdown(report: MultiAgentReport) -> str:
    """
    Convert a MultiAgentReport to a formatted Markdown string.

    Args:
        report: The MultiAgentReport to convert

    Returns:
        Formatted Markdown string
    """
    lines = []

    # Title
    lines.append(f"# Research Report: {report.topic}")
    lines.append("")

    # Metadata
    lines.append("---")
    lines.append(f"**Subtopics Researched:** {len(report.subtopics)}")
    lines.append(f"**Total Sources:** {len(report.all_sources)}")
    lines.append("---")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(report.executive_summary)
    lines.append("")

    # Overall Key Insights
    if report.overall_insights:
        lines.append("## Key Insights")
        lines.append("")
        for i, insight in enumerate(report.overall_insights, 1):
            lines.append(f"### {i}. {insight.finding}")
            if insight.citations:
                lines.append("")
                lines.append("**Citations:**")
                for citation in insight.citations:
                    lines.append(f"- {citation}")
            lines.append("")

    # Consensus Points
    if report.consensus_points:
        lines.append("## Consensus Points")
        lines.append("")
        lines.append("Areas where multiple sources agree:")
        lines.append("")
        for point in report.consensus_points:
            lines.append(f"- {point}")
        lines.append("")

    # Findings by Subtopic
    if report.subtopic_findings:
        lines.append("## Findings by Subtopic")
        lines.append("")

        for findings in report.subtopic_findings:
            lines.append(f"### {findings.subtopic}")
            lines.append("")
            lines.append(f"**Summary:** {findings.summary}")
            lines.append("")

            if findings.key_insights:
                lines.append("**Key Insights:**")
                lines.append("")
                for insight in findings.key_insights:
                    lines.append(f"- {insight.finding}")
                    if insight.citations:
                        for citation in insight.citations[:2]:  # Limit to 2 inline
                            lines.append(f"  - Source: {citation}")
                lines.append("")

            if findings.researcher_notes:
                lines.append(f"**Notes:** {findings.researcher_notes}")
                lines.append("")

            # Top sources for this subtopic
            if findings.sources:
                lines.append("**Top Sources:**")
                lines.append("")
                for source in findings.sources[:3]:  # Top 3 per subtopic
                    lines.append(f"- [{source.title}]({source.url})")
                    if source.score:
                        lines.append(f"  - Relevance: {source.score:.3f}")
                lines.append("")

    # Conflicts and Gaps
    if report.conflicts_and_gaps:
        lines.append("## Conflicts & Gaps in Literature")
        lines.append("")
        lines.append(report.conflicts_and_gaps)
        lines.append("")

    # Top Sources Overall
    if report.top_sources:
        lines.append("## Top Sources")
        lines.append("")
        for i, source in enumerate(report.top_sources, 1):
            lines.append(f"### {i}. {source.title}")
            lines.append("")
            lines.append(f"**URL:** {source.url}")
            if source.score:
                lines.append(f"**Relevance Score:** {source.score:.4f}")
            if source.why_matters:
                lines.append(f"**Why It Matters:** {source.why_matters}")
            if source.snippet:
                lines.append("")
                lines.append(f"> {source.snippet[:300]}{'...' if len(source.snippet) > 300 else ''}")
            lines.append("")

    # All Citations
    if report.all_sources:
        lines.append("## All Citations")
        lines.append("")
        seen_urls = set()
        for source in report.all_sources:
            if source.url not in seen_urls:
                lines.append(f"- [{source.title}]({source.url})")
                seen_urls.add(source.url)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by ScholarAI Advanced - Multi-Agent Research System*")

    return "\n".join(lines)
